version: '3.4'

networks:
  newsapi:

services:
  newsdb:
    container_name: news-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_password123"
    networks:
      - newsapi

  newsparserapi:
    image: ${DOCKER_REGISTRY-}newsparserapi
    build:
      context: .
      dockerfile: NewsParserApi/Dockerfile
    ports:
      - 8001:80
      - 8002:443
    depends_on:
      - newsdb
    environment:
     - DB_HOST=newsdb
     - DB_NAME=NewsDb
     - DB_SA_PASSWORD=Your_password123 
    networks:
      - newsapi
